# This file demonstrates a Terraform configuration using multiple providers.
# The state.json file is generated by: tofu apply && tofu show -json

resource "random_string" "example" {
  length  = 16
  special = true
  upper   = true
  lower   = true
  numeric = true
}

resource "tls_private_key" "example" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
