name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: 1.26.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -p 10 -f .goreleaser.yml --skip=validate --timeout 60m0s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
