name: Test

on:
  pull_request:

env:
  AWS_REGION: us-west-2
  OIDC_ROLE_ARN: ${{ secrets.OIDC_ROLE_ARN }}
  PULUMI_CONFIG_PASSPHRASE: 123456

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Pulumi Access Token
        id: generate_pulumi_token
        uses: pulumi/auth-actions@141415910c3beb54e03b48e9057c204c97b956f2 # v2.1.0
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
          export-environment-variables: false

      - name: Export AWS Credentials
        uses: pulumi/esc-action@3af4859af8a73a362fb599b944124097d4bb80c5 # v3.1.0
        env:
          PULUMI_ACCESS_TOKEN: ${{ steps.generate_pulumi_token.outputs.pulumi-access-token }}
        with:
          environment: logins/pulumi-ci

      - name: Unset PULUMI_ACCESS_TOKEN
        run: echo "PULUMI_ACCESS_TOKEN=" >> $GITHUB_ENV

      - name: Set up Pulumi
        uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Setup local Pulumi backend
        run: |
          pulumi login --local

      - name: Warmup pulumi new
        # TODO[pulumi/pulumi#21285]
        run: |
          mkdir /tmp/project
          pulumi new typescript --dir /tmp/project --yes

      - name: Run tests
        run: go test -v ./...
